### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by sprabhakaran** [socketio/engine.io-server-java#17] opened 2019-05-16 07:47 UTC
I have to use engine.io-server-java in my project. When I initiate the **eio** function, The request has failed and thrown 400 Bad requests. How do I debug this problem? Are there any documents available for engine.io-server-java?

**Error**
 

> WebSocket connection to 'ws://localhost:8080/engine.io/?EIO=3&transport=websocket&sid=Mg_ZSd5' failed: Error during WebSocket handshake: Unexpected response code: 400
> WS.doOpen @ engine.io.js:4403
> Transport.open @ engine.io.js:1700
> Socket.probe @ engine.io.js:468
> Socket.onOpen @ engine.io.js:489
> Socket.onHandshake @ engine.io.js:549
> Socket.onPacket @ engine.io.js:511
> (anonymous) @ engine.io.js:346
> Emitter.emit @ engine.io.js:3096
> Transport.onPacket @ engine.io.js:1765
> callback @ engine.io.js:1510
> exports.decodePayload @ engine.io.js:2199
> Polling.onData @ engine.io.js:1514
> (anonymous) @ engine.io.js:1071
> Emitter.emit @ engine.io.js:3096
> Request.onData @ engine.io.js:1244
> Request.onLoad @ engine.io.js:1311
> xhr.onreadystatechange @ engine.io.js:1197

**Request Header**

**Code:**

```java
@WebServlet("/engine.io/*")
public class SocketIO extends HttpServlet {
	private final EngineIoServer server = new EngineIoServer();
	
	@Override
	protected void service(HttpServletRequest request, HttpServletResponse response) throws IOException {
        server.handleRequest(request, response);
        server.on("connection", new Emitter.Listener() {
			@Override
			public void call(Object... arg0) {
				System.out.println("Socket connected");			
			}
		});
    }
}
```

**Client Code:**
```js
var io = eio("http://localhost:8080", {transport: ["websocket"], upgrade: true, reconnection: false});
```

**Comment by trinopoty** [comment] 2019-05-16 16:26
Please refer to [WebSocket documentation](https://socketio.github.io/engine.io-server-java/using.html#websocket-connections) on how to setup websocket handling.

**Comment by sprabhakaran** [comment] 2019-05-16 16:45
@trinopoty I tried both ways of implementation, but, I got the same 400 issues. The tomcat server didn't log the 400 request's trace.  So, I can't able to close to the problem.

**Comment by trinopoty** [comment] 2019-05-16 21:09
Try setting breakpoints in the websocket handler. If that doesn't work, the request isn't reaching the server and the problem is elsewhere.
What version of tomcat are you using?

**Comment by sprabhakaran** [comment] 2019-05-17 04:39
**Tomcat version:** 9.x
**Java version:** 1.8.x
**engine.io-server-java:** master source
**engine.io.js:** master source

**Comment by trinopoty** [comment] 2019-05-17 09:27
If the websocket handler is never being invoked, there's some problem in configuring tomcat.
Try to get a normal websocket connection first and then build up from that.

**Comment by sprabhakaran** [comment] 2019-05-17 10:03
I tried with the normal WebSocket connection and It works. 

I found the below code in handleRequest method. Is this correct? I assumed that transport param accepts multiple values (websocket and polling). But, this check always checking polling content alone. In my client code, I passed the websocket string. The below always throw 400 error.

```
if (!query.containsKey("transport") || !query.get("transport").equals("polling")) {
            sendErrorMessage(response, ServerErrors.UNKNOWN_TRANSPORT);
            return;
 }

```

@trinopoty  The given docs are not enough to use(even I can't make an upgrade the HttpRequest) and it really painful to understand the workflow. Can you please post sample code, at least the HelloWorld example.  

Curious to know, does anyone using this framework now?

**Comment by trinopoty** [comment] 2019-05-17 12:40
That is for the http request handling only. There's a separate handler for websocket connections named `handleWebsocket`. You need to setup websocket handling and call that.

**Comment by trinopoty** [comment] 2019-05-17 12:42
[This code](https://socketio.github.io/engine.io-server-java/using.html#generic-server) should work for tomcat.

> Curious to know, does anyone using this framework now?
Yes, I happen to be using this in a production environment right now.

**Comment by trinopoty** [comment] 2019-05-17 12:44
I'll try to get some examples included.

**Comment by sprabhakaran** [comment] 2019-05-17 12:49
@trinopoty  Please check the below code that I have used handleWebsocket method. Now I getting different error,

> engine.io.js:4403 WebSocket connection to 'ws://localhost:8080/engine.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 200


Am I missed anything in the below code?

```
package com.ide.socketio;

import java.io.IOException;
import java.util.Map;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import io.socket.engineio.server.EngineIoServer;
import io.socket.engineio.server.EngineIoWebSocket;
import io.socket.parseqs.ParseQS;

@WebServlet("/engine.io/*")
public class EchoServlet extends HttpServlet {

	private final EngineIoServer server = new EngineIoServer();

	@Override
	protected void service(HttpServletRequest request, HttpServletResponse response) throws IOException {
		final Map<String, String> query = ParseQS.decode(request.getQueryString());
		server.handleWebSocket(new MyClass(query));
	}

}

class MyClass extends EngineIoWebSocket {

	Map<String, String> query;

	MyClass(Map<String, String> query) {
		this.query = query;
	}

	@Override
	public Map<String, String> getQuery() {
		return this.query;
	}

	@Override
	public void write(String message) throws IOException {
		System.out.println("write msg called " + message);

	}

	@Override
	public void write(byte[] message) throws IOException {
		// TODO Auto-generated method stub

	}

	@Override
	public void close() {
		// TODO Auto-generated method stub
		System.out.println("-------------  closed ");

	}

}

```

**Comment by trinopoty** [comment] 2019-05-17 12:53
The mechanism for registering websocket endpoints are different than http endpoints.
All the code needed to get websocket working is given [here](https://socketio.github.io/engine.io-server-java/using.html#generic-server).
Try that code out and let me know.

**Comment by sprabhakaran** [comment] 2019-05-17 13:23
Dear @trinopoty  I tried given code snippet. Yes, The code is working. The HTTP request has been upgraded. 

Thanks a lot.

**Comment by sprabhakaran** [comment] 2019-05-20 10:57
Dear @trinopoty 

After the setup the connection establishing works without error. But, the data transmission is not working. I enabled the client debugger and find the below log logs,

```js
engine.io.js:3394 engine.io-client:socket creating transport "websocket" +0ms
engine.io.js:3394 engine.io-client:socket setting transport websocket +27ms
engine.io.js:3394 engine.io-client:socket socket receive: type "error", data "parser error" +130ms
engine.io.js:3394 engine.io-client:socket socket error {"code":"parser error"} +1ms
engine.io.js:3394 engine.io-client:socket socket close with reason: "transport error" +1ms

```

Any idea of the above error?

**Comment by trinopoty** [comment] 2019-05-21 08:29
"transport error" may be caused by connecting to websocket of a different protocol (not engine.io) or network issues.
If you're using Chrome, you can go into the Developer Console > Network tab and see exactly what data is being transferred.

**Closed** 2019-05-28 12:56 UTC
